services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: page_builder
    platform: linux/amd64
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80:3000"
    volumes:
      - ./app:/var/www/html
    networks:
      - page_builder_network

networks:
  page_builder_network:
    driver: bridge